# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefualtWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefualtWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(66c23178-97dc-427f-bf67-bf07bc1d1dae)'
    appType: 'webApp'
    appName: 'TahaApp'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'
